"""create users,google_accounts,transfer_jobs

Revision ID: 0ad7311e71cd
Revises: d08f3fc2b8e3
Create Date: 2026-07-10 00:15:58.110619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ad7311e71cd'
down_revision: Union[str, Sequence[str], None] = 'd08f3fc2b8e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
    op.create_table('users',
    sa.Column('userId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('email')
    )
    op.create_table('google_accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('gmail_address', sa.String(), nullable=False),
    sa.Column('token_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Lưu nội dung token.json (Nên được mã hóa)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'gmail_address', name='uq_user_gmail')
    )
    op.create_table('transfer_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_gmail', sa.String(), nullable=False),
    sa.Column('source_folder_id', sa.String(), nullable=False),
    sa.Column('dest_gmail', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dest_gmail'], ['users.email'], ),
    sa.ForeignKeyConstraint(['source_gmail'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_jobs')
    op.drop_table('google_accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
